name: "1Live Plan B"
description: "Scrapes 1LIVE Plan B songs (Mon-Thu, 20-23h) and updates a Tidal playlist."
version: "0.1.0"
slug: "plan_b"
url: "https://github.com/paul1911/plan-b"

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

startup: application
boot: auto
init: false

options:
  schedule_time: "04:00"
  spotify_enabled: false
  spotify_client_id: ""
  spotify_client_secret: ""

schema:
  schedule_time: str
  spotify_enabled: bool
  spotify_client_id: str
  spotify_client_secret: str
